config/routes.rb
Shopstr::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  devise_scope :users do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  resources :authentications, :only => [:destroy, :create, :index]
  resources :carts, :only => [:update, :destroy]
  resources :items, :only => :show
  resources :line_items, :only => [:create, :destroy]
  resources :orders, :only => [:new, :show,  :create]
  resources :pages , :only => [:home, :search, :show]
  resources :sections, :only => :show do
    get :filter, :on => :member
  end
  resources :users, :only => :show


  namespace :admin do
    resources :sections do
      get :trigger, :on => :member
      get :autocomplete, :on => :member
      resources :items
      resources :parameters
      collection { post :sort }

    end
    resources :amounts
    resources :line_items
    resources :carts do
      get :add_item, :on => :member
    end
    resources :users, :path => "/users" do
      get :trigger, :on => :member
    end
    resources :orders do
      get :add_item, :on => :member
      get :cancel, :on => :member
      get :complete, :on => :member
    end
    resources :items do
      get :who_bought, :on => :member
      get :duplicate, :on => :member
      get :trigger, :on => :member
      collection { get :parameters_list }
      collection { post :sort }
      collection { post :massacre }
    end
    resources :images
    resources :parameters do
      get :trigger, :on => :member
      collection { post :sort }
      resources :amounts
      collection { get :items_list }
    end
    resources :settings do
      collection do
        put 'update'
      end
    end
    resources :groups do
      resources :users
    end
    resources :pages do
      get :trigger, :on => :member
    end
  end

  get '/auth/:provider/callback' => 'authentications#create'
  #Page.enabled.each do |page|
  #  get "/#{page.uri}" => "pages#show", :id => page.id
  #end
  get '/search', :to => 'pages#search'
  get '/admin', :to => 'admin/pages#home'
  root :to => 'pages#home'
  get '*a', :to => 'errors#routing'
end

app/views/admin/pages/_form.erb
<script type="text/javascript">
    function append_wheel() {
        $('.nicEdit-main img').bind('mousewheel', function (event, delta) {
            var value = delta > 0 ? '+=10' : '-=10';
            $(this).css('width', value);
            return false;
        });
    }
    bkLib.onDomLoaded(function () {
        new nicEditor({buttonList:[
            'bold',
            'italic',
            'underline',
            'strikethrough',
            'fontSize',
            'fontFormat',
            'left',
            'center',
            'right',
            'justify',
            'ol',
            'ul',
            'subscript',
            'superscript',
            'indent',
            'outdent',
            'hr',
            'image',
            'upload',
            'forecolor',
            'bgcolor',
            'link',
            'unlink',
            'removeformat',
            'xhtml'
        ]}).panelInstance('page_content');
        append_wheel()
    });

    $(function () {
        var atoken = $("input[name=authenticity_token]").val();
        var uploader = new plupload.Uploader({
            runtimes:'html5,html4',
            browse_button:'pickfiles',
            container:'container',
            max_file_size:'10mb',
            url:'<%= admin_images_path%>',
            multipart:true,
            multipart_params:{ authenticity_token:atoken},
            filters:[
                {title:"Image files", extensions:"jpg,gif,png,jpeg"}
            ]
        });

        uploader.bind('Init', function (up, params) {
            $('#runtime').html(params.runtime);
        });

        $('#uploadfiles').click(function (e) {
            uploader.start();
            e.preventDefault();
        });

        uploader.init();

        uploader.bind('FilesAdded', function (up, files) {
            $.each(files, function (i, file) {
                $('#filelist').prepend(
                        '<div class="span2 cell" id="' + file.id + '">' +
                                '<div class="img-title">' + plupload.formatSize(file.size) + '<a href="#" class="badge badge-inverse delete" data-method="delete" data-remote="true" rel="nofollow" style="display:none;">X</a></div> ' +
                                '<div class="progress progress-success">' +
                                '<div class="bar" style="width: 0;"></div></div></div>');
            });
        });

        uploader.bind('UploadProgress', function (up, file) {
            $('#' + file.id + " .bar").attr('style', 'width:' + file.percent + '%;');
        });

        uploader.bind('Error', function (up, err) {
            var img_box = $('#' + err.file.id);
            img_box.find('.title').append("Error: " + err.code +
                    ", Message: " + err.message +
                    (err.file ? ", File: " + err.file.name : "")
            );

        });

        uploader.bind('FileUploaded', function (up, file, info) {

            var img_box = $('#' + file.id);
            var response = info['response'].split(':');
            img_box.find('.progress').attr('class', 'img').html('<img src="' + response[2] + '" />');
            img_box.find('.delete').attr('href', '/admin/images/' + response[0]).attr('id', response[0]).show();
            $('.nicEdit-main').append('<img src="' + response[2] + '" />');
            append_wheel();
        });
        $('#container').on('click', '.delete', function () {
            $(this).closest('.cell').remove();
        });
        $('body').on('click', '.insert', function () {
            var img = $(this).closest('.cell').find('img').clone();
            $('.nicEdit-main').append(img);
            return false;
        });

    });
</script>
<%= form_for [:admin, @page], :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.error_messages %>
    <fieldset>
      <div class="form-group">
        <label class="control-label" for="page_title">Название</label>

        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label" for="page_uri">URI</label>

        <div class="controls">
          <%= f.text_field :uri %>
          <span class="help-inline">На латинице</span>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label" for="page_enabled">Показывать?</label>

        <div class="controls">
          <%= f.check_box :enabled %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label" for=page_meta_title>Мета-заголовок</label>

        <div class="controls">
          <%= f.text_field :meta_title %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label" for=page_meta_keywords>Ключевые слова</label>

        <div class="controls">
          <%= f.text_field :meta_keywords %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label" for=page_meta_description>Мета-описание</label>

        <div class="controls">
          <%= f.text_area :meta_description, :size => '40x5' %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label" for=pickfiles>Картинки для текста</label>

        <div class="controls">
          <div id="container">
            <a id="pickfiles" href="#" class="btn btn-default">Выберите файлы</a>
            <a id="uploadfiles" href="#" class="btn btn-default btn-primary">Загрузить</a>
            <span id="runtime" class="label label-info"></span>

            <div id="filelist">
              <%= render partial: 'admin/images/page_image', collection: @new_images, as: 'image' %>
            </div>
            <div id="item-images">
              <%= render partial: 'admin/images/page_image', collection: @page.images, as: 'image' %>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label" for="page_content">Содержимое</label>

        <div class="controls">
          <%= f.text_area :content, class: 'col-md-10' %>
        </div>
      </div>
      <div class="form-actions">
        <%= f.submit 'Сохранить', class: 'btn btn-default btn-primary' %>
      </div>
    </fieldset>
<% end %>

app/views/admin/pages/_page.erb
<%= content_tag_for :tr,page do %>
    <td>
      <%= link_to page.title, edit_admin_page_path(page) %>
    </td>
    <td>
      <%= "[#{page.uri}]"%>
    </td>
    <% if page.enabled? %>
        <td><%= link_to raw("<i class='glyphicon glyphicon-off'></i>"), trigger_admin_page_path(:id => page, :field => :enabled), title: 'Включено', remote: true, :class => "active btn btn-default btn-xs enabled" %></td>
    <% else %>
        <td><%= link_to raw("<i class='glyphicon glyphicon-off'></i>"), trigger_admin_page_path(:id => page, :field => :enabled), title: 'Выключено', remote: true, :class => "btn btn-default btn-xs enabled" %></td>
    <% end %>
    <td><%= link_to raw("<i class='glyphicon glyphicon-trash glyphicon glyphicon-white'></i>"), admin_page_path(page), :remote => true, method: :delete, :class => 'btn btn-default btn-danger btn-xs delete' %></td>

<% end %>

app/views/admin/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/admin/pages/home.html.erb
<script>
    $(function () {
        Highcharts.setOptions({
            global:{
                useUTC:false
            },
            lang:{
                months:['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
                shortMonths:['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек']
            }
        });
        new Highcharts.Chart({
            chart:{ renderTo:'money_chart' },
            title:{ text:'Доход по дням' },
            xAxis:{ type:'datetime',
                dateTimeLabelFormats:{ // don't display the dummy year
                    day:'%d.%m'
                }
            },
            yAxis:{
                title:{ text:'Рубли' }
            },
            tooltip:{
                formatter:function () {
                    return Highcharts.dateFormat("%d.%m.%y", this.x) + ': ' +
                            Highcharts.numberFormat(this.y, 0, "\'") + ' руб';
                }
            },
            series:[
                <% { "Выполненные заказы" => Order.unscoped.completed, "Новые заказы" => Order.unscoped.newest }.each do |name, order| %>
                {
                    name:"<%= name %>",
                    pointInterval: <%= 1.day * 1000 %>,
                    pointStart: <%= 40.days.ago.at_midnight.to_i * 1000 %>,
                    data: <%= orders_chart_series(order, 40.days.ago) %>
                },
                <% end %>
            ]
        });
        new Highcharts.Chart({
            chart:{
                renderTo:'months_chart',
                type:'line'
            },
            title:{
                text:'Доход по месяцам'
            },
            xAxis:{type:'datetime',
                dateTimeLabelFormats:{
                    day:'%d.%m',
                    month:'%m'
                }
            },
            yAxis:{
                title:{
                    text:'Рубли'
                }
            },
            tooltip:{
                formatter:function () {
                    return Highcharts.dateFormat("%B", this.x) + ': ' +
                            Highcharts.numberFormat(this.y, 0, "\'") + ' руб';
                }
            },
            plotOptions:{
                line:{
                    dataLabels:{
                        enabled:true
                    }
                }
            },
            series:[
                <% { "Выполненные заказы" => Order.unscoped.completed }.each do |name, orders| %>
                {
                    name:"<%= name %>",
                    pointStart: <%= (3.months.ago.beginning_of_month+15.days).to_i * 1000 %>,
                    pointInterval: <%= 1.month * 1000 %>,
                    data:<%= orders_chart_month_series(orders, 3.months.ago.beginning_of_month) %>
                },
                <% end %>
            ]
        });
        new Highcharts.Chart({
            chart:{
                renderTo:'newest_chart',
                type:'line'
            },
            title:{
                text:'Выполненные заказы по месяцам'
            },
            xAxis:{type:'datetime'
            },
            yAxis:[
                { // Primary yAxis
                    min:1,
                    labels:{
                        formatter:function () {
                            return this.value + 'р';
                        },
                        style:{
                            color:'#89A54E'
                        }
                    },
                    title:{
                        text:'Рубли',
                        style:{
                            color:'#89A54E'
                        }
                    }
                },
                { // Secondary yAxis
                    title:{
                        text:'Заказы',
                        style:{
                            color:'#4572A7'
                        }
                    },
                    labels:{
                        formatter:function () {
                            return this.value + ' шт.';
                        },
                        style:{
                            color:'#4572A7'
                        }
                    },
                    opposite:true
                }
            ],
            tooltip:{
                formatter:function () {
                    return Highcharts.dateFormat("%B", this.x) + ': ' +
                            Highcharts.numberFormat(this.y, 0) +
                            (this.series.name == 'Сумма заказов' ? ' руб' : ' шт');
                }
            },
            legend:{
                layout:'vertical',
                align:'left',
                x:120,
                verticalAlign:'top',
                y:100,
                floating:true,
                backgroundColor:'#FFFFFF'
            },
            plotOptions:{
                line:{
                    dataLabels:{
                        enabled:true
                    }
                }
            },
            series:[
                {
                    name:'Количество заказов',
                    pointStart: <%= (3.months.ago.beginning_of_month+15.days).to_i * 1000 %>,
                    pointInterval: <%= 1.month * 1000 %>,
                    color:'#4572A7',
                    type:'column',
                    yAxis:1,
                    data:<%= orders_numbers_chart_series(Order.unscoped.completed, 3.months.ago.beginning_of_month) %>
                },
                {
                    name:"Сумма заказов",
                    pointStart: <%= (3.months.ago.beginning_of_month+15.days).to_i * 1000 %>,
                    pointInterval: <%= 1.month * 1000 %>,
                    color:'#89A54E',
                    type:'spline',
                    data:<%= orders_chart_month_series(Order.unscoped.completed, 3.months.ago.beginning_of_month) %>
                }
            ]
        });
    });
</script>
<div>
  <%= link_to raw("Новых заказов <span class='badge badge-info'>#{@new_counter}</span>"), admin_orders_path(:status => 0) %>
</div>
<%#= orders_chart_month_series(Order.unscoped.completed, 5.months.ago) %>
<%# orders=Order.unscoped.completed.where(:updated_at => 16.months.ago.beginning_of_month.at_midnight..Time.zone.now.end_of_day).select("date_part('month', updated_at) as month, sum(totals) as totals").group("month") %>
<%#= orders.map { |o| o} %>
<%#= 3.months.ago.beginning_of_month.to_i %>

<div id="months_chart" style="width: 1024px; height: 300px;"></div>
<div id="money_chart" style="width: 1024px; height: 300px;"></div>
<div id="newest_chart" style="width: 1024px; height: 300px;"></div>

app/views/admin/pages/index.erb
<script>
    $(function () {
        $('.delete').click(function () {
            $(this).closest('tr').hide();
        });
    });
</script>
<%= link_to raw("<i class='glyphicon glyphicon-plus glyphicon glyphicon-white'></i>страница"), new_admin_page_path, :class => 'btn btn-default btn-primary add-button' %>
<div id="pages">
  <table class="table auto table-condensed">
    <tbody>
    <%= render @pages %>
    </tbody>
  </table>
</div>

app/views/admin/pages/search.erb
<% content_for :main do %>
    <% unless @items.empty? %>
        <h1><%= @title %></h1>
        <ul>
          <%= render @items %>
        </ul>
    <% else %>
        <h4><%= "К сожалению, нет товаров, которые соответствуют параметрам поиска. Попробуйте еще раз с другими параметрами" %></h4>
    <% end %>
<% end %>

app/views/admin/pages/trigger.js.erb
var page = $('#page_<%=@page.id %>');
var enabled = page.find('.enabled');

<% if @page.enabled? %>
enabled.addClass('active').attr('title', 'Включен');
<% else %>
enabled.removeClass('active').attr('title', 'Выключен');
<% end %>