config/routes.rb
Shopstr::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  devise_scope :users do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  resources :authentications, :only => [:destroy, :create, :index]
  resources :carts, :only => [:update, :destroy]
  resources :items, :only => :show
  resources :line_items, :only => [:create, :destroy]
  resources :orders, :only => [:new, :show,  :create]
  resources :pages , :only => [:home, :search, :show]
  resources :sections, :only => :show do
    get :filter, :on => :member
  end
  resources :users, :only => :show


  namespace :admin do
    resources :sections do
      get :trigger, :on => :member
      get :autocomplete, :on => :member
      resources :items
      resources :parameters
      collection { post :sort }

    end
    resources :amounts
    resources :line_items
    resources :carts do
      get :add_item, :on => :member
    end
    resources :users, :path => "/users" do
      get :trigger, :on => :member
    end
    resources :orders do
      get :add_item, :on => :member
      get :cancel, :on => :member
      get :complete, :on => :member
    end
    resources :items do
      get :who_bought, :on => :member
      get :duplicate, :on => :member
      get :trigger, :on => :member
      collection { get :parameters_list }
      collection { post :sort }
      collection { post :massacre }
    end
    resources :images
    resources :parameters do
      get :trigger, :on => :member
      collection { post :sort }
      resources :amounts
      collection { get :items_list }
    end
    resources :settings do
      collection do
        put 'update'
      end
    end
    resources :groups do
      resources :users
    end
    resources :pages do
      get :trigger, :on => :member
    end
  end

  get '/auth/:provider/callback' => 'authentications#create'
  #Page.enabled.each do |page|
  #  get "/#{page.uri}" => "pages#show", :id => page.id
  #end
  get '/search', :to => 'pages#search'
  get '/admin', :to => 'admin/pages#home'
  root :to => 'pages#home'
  get '*a', :to => 'errors#routing'
end

app/models/order.rb
# -*- encoding : utf-8 -*-
class Order < ActiveRecord::Base
  before_save :add_hash, :count_total
  has_many :line_items, :dependent => :destroy
  belongs_to :user
  accepts_nested_attributes_for :line_items
  default_scope { order('orders.created_at DESC').joins("LEFT JOIN line_items li ON li.order_id = orders.id").select("orders.*, sum(li.quantity) as quantity").group("orders.id") }
  scope :newest, where(:status => 0)
  scope :checked, where(:status => 1)
  scope :completed, where(:status => 2)
  scope :deleted, where(:status => 3)

  PAYMENT_TYPES = [["Оплата наличными курьеру", 0]]
  STATUS= [["Новый", 0], ["Принят", 1], ["Выполнен", 2], ["Удален", 3]]

  validates :name, :address, :phone, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES.map { |key, value| value }
  #validates :phone, :length => 1..10

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  #def total_items
  #  line_items.sum(:quantity)
  #end

  def self.get(field, value)
    where(field => value)
  end

  def self.in_group(group)
    threshold=group.threshold
    next_threshold=Group.where("threshold > ? AND wholesale='t'", threshold).first.try(:threshold)
    unless next_threshold.blank?
      orders=Order.where(:totals => (threshold..next_threshold)).order('created_at DESC')
    else
      orders=Order.where("totals>=?", threshold).order('created_at DESC')
    end
    orders
  end

  def total
    line_items.sum("price*quantity").to_i
  end

  private

  def add_hash
    self.email_hash=Digest::SHA2.hexdigest("#{self.email}--#{Time.now.utc}")
  end

  def count_total
    self.totals=self.total unless self.new_record?
  end

end

app/controllers/admin/orders_controller.rb
# -*- encoding : utf-8 -*-
class Admin::OrdersController < Admin::BaseController
  before_filter :sections_tree, :except => [:destroy, :cancel, :complete, :add_item]

  def index
    @title="Заказы"
    @orders=Order.page(params[:page]).per(10)
    if params[:status]
      @orders=@orders.get(:status, params[:status])
    end
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @items=Item.enabled
    @cart=current_cart
    @order = Order.new(:status => 1)
    @title="Оформление нового заказа"
    @statuses=Hash[Order::STATUS.map { |key, value| [value, key] }]
    @delivery=Setting.find_by_option("delivery_value").value.to_i
    @threshold=Setting.find_by_option("delivery_limit").value.to_i
    @discount=0
    @total_discount=@cart.total*(100-@discount)/100
    @total_discount_delivery=@total_discount
    @total_discount_delivery+=@delivery unless @total_discount>@threshold
  end

  def edit
    @title=""
    @order=Order.find(params[:id])
    @pay_types=Hash[Order::PAYMENT_TYPES.map { |key, value| [value, key] }]
    @statuses=Hash[Order::STATUS.map { |key, value| [value, key] }]
    @delivery=Setting.find_by_option("delivery_value").value.to_i
    @threshold=Setting.find_by_option("delivery_limit").value.to_i

    user=@order.try(:user)
    @group=user.group if user

    #discount
    if @group && @order.discount==0
      @order.discount=@group.discount
    end
    @discount=@order.discount.to_i
    @total_discount=@order.total*(100-@discount)/100
    @total_discount_delivery=@total_discount
    @total_discount_delivery+=@delivery unless @total_discount>@threshold

    @items=Item.enabled

    if session[:prev]||session[:next]
      @prev=session[:prev]
      @next=session[:next]
      session[:prev]=nil
      session[:next]=nil
    else
      @prev= Order.unscoped.where("id > ? AND status = ?", params[:id], @order.status).order('created_at ASC').first
      @next= Order.unscoped.where("id < ? AND status = ?", params[:id], @order.status).order('created_at DESC').first
    end
  end

  def create
    @order = Order.new(params[:order])
    if @order.save
      @order.add_line_items_from_cart(current_cart)
      Cart.destroy(cookies.signed[:cart_id])
      cookies.permanent.signed[:cart_id] = nil

      unless @order.email.blank?
        Thread.new { Notifier.order_received(@order).deliver }
      end
      redirect_to('/', :notice => "Спасибо за ваш заказ, #{@order.name}")
    else
      @title="Оформление нового заказа"
      @items=Item.enabled
      @cart=current_cart
      @statuses=Hash[Order::STATUS.map { |key, value| [value, key] }]
      @delivery=Setting.find_by_option("delivery_value").value.to_i
      @threshold=Setting.find_by_option("delivery_limit").value.to_i
      @discount=@order.discount
      @total_discount=@cart.total*(100-@discount)/100
      @total_discount_delivery=@total_discount
      @total_discount_delivery+=@delivery unless @total_discount>@threshold
      render :new
    end
  end

  def update
    @order = Order.find(params[:id])
    user=@order.try(:user)
    @group=user.group if user
    #discount
    @discount=@order.discount
    if @group && @discount==0
      @discount=@group.discount
    end
    respond_to do |format|
      params[:order][:prev_status]=@order.status
      if @order.update_attributes(params[:order])
        case @order.status
          when 1
            Thread.new { Notifier.order_accepted(@order).deliver }
          when 2
            if user
              user.update_attribute(:spent, user.sum_of_done)
            end
        end

        session[:prev]= Order.unscoped.where("id > ? AND status = ?", params[:id], @order.prev_status).order('created_at ASC').first
        session[:next]= Order.unscoped.where("id < ? AND status = ?", params[:id], @order.prev_status).order('created_at DESC').first

        format.html { redirect_to :back, notice: 'Заказ был успешно обновлен' }
        format.js
      else
        format.html { render action: "edit", notice: 'Ошибка' }
        format.js
      end
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to admin_orders_url }
      format.json { head :ok }
    end
  end

  def cancel
    @order = Order.find(params[:id])
    @order.update_attribute(:status, 3)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def complete
    @order = Order.find(params[:id])
    @order.update_attribute(:status, 2)
    user=@order.try(:user)
    user.update_attribute(:spent, user.sum_of_done) if user

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def add_item
    @order=Order.find(params[:id])
    item_id=params[:item_id]
    if item_id
      current_item = @order.line_items.find_by_item_id(item_id)
      if current_item
        current_item.quantity += 1
        current_item.save
      else
        @order.line_items.create(:item_id => item_id, :price => Item.find(item_id).price)
      end
    end
    respond_to do |format|
      format.js
    end
  end
end


app/controllers/orders_controller.rb
# -*- encoding : utf-8 -*-
class OrdersController < ApplicationController
  before_filter :pages_list

  def show
    @order = Order.find(params[:id])
    @statuses=Hash[Order::STATUS.map { |key, value| [value, key] }]
    @pay_types=Hash[Order::PAYMENT_TYPES.map { |key, value| [value, key] }]
    @delivery=Setting.find_by_option("delivery_value").value.to_i
    @threshold=Setting.find_by_option("delivery_limit").value.to_i
    @discount= @order.discount.to_i
    @total_discount=@order.total*(100-@discount)/100
    @total_discount_delivery=@total_discount
    @total_discount_delivery+=@delivery unless @total_discount>@threshold
    unless current_user==@order.user||params[:email_hash]==@order.email_hash
      redirect_to(root_path)
    else
      respond_to do |format|
        format.html # show.html.erb
        format.js
      end
    end
  end

  def new
    @order_cart = current_cart
    @sections = Section.tree
    @title="Оформление заказа"
    @delivery=Setting.find_by_option("delivery_value").value.to_i
    @threshold=Setting.find_by_option("delivery_limit").value.to_i
    if not signed_in? or current_user.group.blank?
      @discount=0
    else
      @discount= current_user.group.discount
    end
    @total_discount=@order_cart.total.to_i*(100-@discount)/100
    @total_discount_delivery=@total_discount
    @total_discount_delivery+=@delivery unless @total_discount>@threshold
    if @order_cart.line_items.empty?
      redirect_to '/', :notice => "Your cart is empty"
      return
    end

    if signed_in?
      @order = Order.new(:name => current_user.last_order.try(:name),
                         :email => current_user.email,
                         :address => current_user.last_order.try(:address),
                         :phone => current_user.last_order.try(:phone))
    else
      @order = Order.new
    end

    respond_to do |format|
      format.html { render '_form' }
      format.json { render json: @order }
    end
  end

  def create
    @order = Order.new(params[:order])
    @order.user=current_user
    @order.totals=current_cart.total
    if @order.save
      @order.add_line_items_from_cart(current_cart)
      Cart.destroy(cookies.signed[:cart_id])
      cookies.permanent.signed[:cart_id] = nil
      unless @order.email.blank?
        Thread.new { Notifier.order_received(@order).deliver }
      end
      redirect_to('/', :notice => "Спасибо за ваш заказ, #{@order.name}!")
    else
      render action: "new"
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def orders_chart_series(orders, start_time)
    orders_by_day = orders.where(:updated_at => start_time.beginning_of_day..Time.zone.now.end_of_day)
    .group("date(updated_at)")
    .select("date(updated_at) as updated_at, sum(totals) as totals")
    (start_time.to_date..Date.today).map do |date|
      order = orders_by_day.detect { |order| order.updated_at.to_date == date }
      order && order.totals.to_i || 0
    end
  end
def orders_chart_month_series(orders,start_time)
    orders_by_month = orders.where(:updated_at => start_time.at_midnight..Time.zone.now.end_of_day)
    .select("date_trunc('month', updated_at) as month, sum(totals) as totals").group("month")

    (start_time.month..Date.today.month).map do |month|
      order = orders_by_month.detect { |order| order.month.to_date.month == month }
      order && order.totals.to_i || 0
    end
  end
def orders_numbers_chart_series(orders,start_time)
    orders_by_month = orders.where(:updated_at => start_time.at_midnight..Time.zone.now.end_of_day)
    .select("date_trunc('month', updated_at) as month, COUNT(id) as counter").group("month")

    (start_time.month..Date.today.month).map do |month|
      order = orders_by_month.detect { |order| order.month.to_date.month == month }
      order && order.counter.to_i || 0
    end
  end
end

app/views/admin/orders/_order.erb
<%= content_tag_for :tr, order do %>

    <td>
      <%= order.created_at.stamp("%d.%m.%y") %>
      <i class='glyphicon glyphicon-time'></i>
      <%= order.created_at.stamp("%H:%M") %>
    </td>
    <td><%= link_to "Заказ №#{order.id}", edit_admin_order_path(order) %></td>
    <td><%= order.name %></td>
    <td class="right"><span class="badge badge-info"><%= order.quantity.to_i %></span></td>
    <td class="right"><%= order.total.to_i %>р</td>

    <% if [2, 3].include?(order.status) %>
        <td><%= content_tag :p, raw("<i class='glyphicon glyphicon-ok glyphicon glyphicon-white'></i>"), :class => 'btn btn-default btn-success disabled btn-xs', :title => "Установить статус 'Выполнен'" %></td>
    <% else %>
        <td><%= link_to raw("<i class='glyphicon glyphicon-ok glyphicon glyphicon-white'></i>"), complete_admin_order_path(order), :class => 'btn btn-default btn-success btn-xs', :title => "Установить статус 'Выполнен'" %></td>
    <% end %>

    <% if [2, 3].include?(order.status) %>
        <td><%= content_tag :p, raw("<i class='glyphicon glyphicon-trash glyphicon glyphicon-white'></i>"), class: 'disabled btn btn-default btn-danger btn-xs', :title => 'Деактивирован' %></td>
    <% else %>
        <td><%= link_to raw("<i class='glyphicon glyphicon-trash glyphicon glyphicon-white'></i>"), cancel_admin_order_path(order), class: 'btn btn-default btn-danger btn-xs', :title => 'В активном состоянии' %></td>
    <% end %>
    <td><%= link_to raw("<i class='glyphicon glyphicon-envelope'></i>"), admin_orders_path(:field => :email, :value => order.email), :class => 'btn btn-default btn-xs', :title => 'Найти по email' %></td>
<% end %>

app/views/admin/orders/add_item.js.erb
$('#container').load('/admin/orders/<%= @order.id %>/edit #items');

app/views/admin/orders/edit.html.erb
<script>
    $(function () {
        var delivery = +$('#delivery').html();
        var threshold = +$('#threshold').html();

        $("#container").on("keyup", "#discount", function () {

            var discount = +$(this).val();
            var total = $('#total');
            var total_value = +total.html();
            var total_discount = Math.round(total_value * (100 - discount) / 100);
            $("#total-discount").html(total_discount);
            var total_discount_delivery = $('#total-discount-delivery');
            var total_discount_delivery_new = total_discount;
            if (!(total_discount > threshold)) {
                total_discount_delivery_new += delivery;
            }
            total_discount_delivery.html(total_discount_delivery_new);
        });
        $("#container").on("click", "#discount", function () {
            $(this).keyup();
        });

        <!-- реакция на выбор товара в списке добавления: модифицируется ссылка, -->
        <!-- ведущая на функцию добавления, нажимается, подгрузка товаров -->
        $("#add-item-select").on("change", '#item_id', function () {
            var item_id = +$(this).attr('value');
            var href = '/admin/orders/<%= @order.id%>/add_item?item_id=' + item_id;
            $('#add-item-link').attr('href', href).click();
            $(this).prop('selectedIndex',0);
        });

        <!-- реакция на изменение количества товара: -->
        <!-- пересчет всего, чего можно, отправка формы -->
        $("#container").on("keyup", ".quantity", function () {
            var quantity = +$(this).val();
            var line_item = $(this).closest("tr");
            var cost = line_item.find('.cost');
            var price = +line_item.find('.price').html();
            var discount = +$("#discount").val();
            var cost_old = +cost.html();
            var cost_new = price * quantity;
            cost.html(cost_new);
            var total = $('#total');
            var total_old = +total.html();
            var total_new = total_old + cost_new - cost_old;
            total.html(total_new);
            var total_discount = Math.round(total_new * (100 - discount) / 100);
            $('#total-discount').html(total_discount);
            var total_discount_delivery = $('#total-discount-delivery');
            var total_discount_delivery_new = total_discount;
            if (!(total_discount > threshold)) {
                total_discount_delivery_new += delivery;
            }
            total_discount_delivery.html(total_discount_delivery_new);
            $("#discount").keyup();
        });
        <!-- реакция на выбор товара в списке добавления -->
        $("#container").on("mouseup", ".quantity", function () {
            $(this).keyup();
        });
        $("#container").on('click',".delete", function () {
            var cost=+$(this).closest('tr').find('.cost').html();
            var total = $('#total');
            var total_old=+total.html();
            var total_new=total_old-cost;
            total.html(total_new);
            $(this).closest('tr').remove();
            $("#discount").keyup();
        });
    });
</script>
<div id="edit-order">
  <%= link_to 'добавить', add_item_admin_order_path(@order, :item_id => @items[1].id), :remote => true, :id => "add-item-link", :style => "display:none;" %>
  <%= form_for [:admin, @order] do |f| %>
      <h2><%= "Заказ №#{@order.id}" %>
        <span class='label label-info'><%= @statuses[f.object.status] %></span>
      </h2>

      <div class="left span8">
        <ul class="pager">
          <% unless @prev.blank? %>
              <% prev_status=@statuses[@prev.status] %>
              <li class="previous">
                <%= link_to "← '#{prev_status}' позже ", edit_admin_order_path(@prev) %>
              </li>
          <% end %>
          <% unless @next.blank? %>
              <% next_status= @statuses[@next.status] %>
              <li class="next">
                <%= link_to "'#{next_status}' раньше →", edit_admin_order_path(@next) %>
              </li>
          <% end %>
        </ul>
        <div class="alert alert-info">
          Порог доставки: <b id="threshold"><%= @threshold %></b> руб <br/>
          Стоимость доставки: <b id="delivery"><%= @delivery %></b> руб
        </div>
        <div id="add-item-select">
          <%= select_tag :item_id, options_from_collection_for_select(@items, :id, :title), :prompt => "Добавьте товар" %>
        </div>
        <div id="container">
        <% unless @order.line_items.empty? %>
            <table id="items" class="table table-condensed">
              <tbody>
              <%= f.fields_for :line_items do |builder| %>
                  <% render builder.object, :f => builder %>
              <% end %>
              <tr>
                <td colspan=4 class="right">
                  Всего: <b id="total"><%= @order.total %></b>р
                </td>
                <td></td>
              </tr>
              <tr>
                <td colspan=4 class="right">
                  Всего + скидка: <b id="total-discount"><%= @total_discount %></b>р
                </td>
                <td class="center">
                  <%= f.number_field :discount, style: 'width:30px;', title: 'Скидка', id: "discount" %>%
                </td>
              </tr>
              <tr>
                <td colspan="4" class="right">
                  Всего + скидка + доставка: <b id='total-discount-delivery'><%= @total_discount_delivery %></b>р
                </td>
                <td></td>
              </tr>
              </tbody>
            </table>
        <% end %>
        </div>
          <%= f.text_area :manager_comment, :placeholder => "Комментарий менеджера", :rows => 2 %>

      </div>
      <div class="span3">
        <blockquote>
          <small>время</small>
          <p>
            <% if @order.created_at.today? %>
                <%= @order.created_at.stamp("Сегодня") %>
                <i class='glyphicon glyphicon-time'></i>
                <%= @order.created_at.stamp("%H:%M") %>
            <% else %>
                <%= @order.created_at.stamp("%d.%m.%y") %>
                <i class='glyphicon glyphicon-time'></i>
                <%= @order.created_at.stamp("%H:%M") %>
            <% end %>
          </p>
          <small>адрес</small>
          <p>
            <%= @order.address %>
          </p>
          <% unless @order.email.blank? %>
              <small>email</small>
              <p>
                <%= @order.email %>
              </p>
          <% end %>
          <small>телефон</small>
          <p>
            <%= @order.phone %>
          </p>
          <small>оплата</small>
          <p>
            <%= @pay_types[@order.pay_type] %>
          </p>
          <% unless @group.blank? %>
              <small>группа</small>
              <p>
                <%= link_to(@group.title, admin_group_path(@group)) %>
              </p>
          <% end %>
          <% unless @order.comment.blank? %>
              <small>комментарий</small>
              <p>
                <%= @order.comment %>
              </p>
          <% end %>
        </blockquote>

      </div>
      <div class="col-md-12">
        <%# unless @order.status==2 %>

        <%# end %>
      </div>
      <div class="form-actions col-md-12">
        <%= f.select :status, Order::STATUS  %>  <%= f.submit 'Сохранить', class: 'btn btn-default btn-primary' %>
      </div>
  <% end %>
</div>

app/views/admin/orders/index.html.erb
<div class="statuses span2">
  <ul class="nav nav-pills nav-stacked">
    <%= filter_link_li "Все заказы", {:status => "clear"} %>
    <%= filter_link_li "Новые", :status => 0 %>
    <%= filter_link_li "Принятые", :status => 1 %>
    <%= filter_link_li "Выполненные", :status => 2 %>
    <%= filter_link_li "Удаленные", :status => 3 %>
  </ul>
</div>
<div id="orders" class="span9">
  <% if @orders.blank? %>
      <h2>Пока пусто</h2>
  <% else %>
      <table class="table auto table-condensed">
        <tbody>
        <%= render @orders %>
        </tbody>
      </table>
      <%= paginate @orders %>
  <% end %>
</div>

app/views/admin/orders/new.html.erb
<script>
    $(function () {
        var delivery = +$('#delivery').html();
        var threshold = +$('#threshold').html();
        <!-- реакция на изменение скидки: пересчет суммы со скидкой, отправка формы -->
        $("#discount").keyup(function () {
            var discount = +$(this).val();
            var total = $('#total');
            var total_value = +total.html();
            var total_discount = Math.round(total_value * (100 - discount) / 100);
            $("#total-discount").html(total_discount);
            var total_discount_delivery = $('#total-discount-delivery');
            var total_discount_delivery_new = total_discount;
            if (!(total_discount > threshold)) {
                total_discount_delivery_new += delivery;
            }
            total_discount_delivery.html(total_discount_delivery_new);
        });
        $("#discount").click(function () {
            $(this).keyup();
        });
        <!-- реакция на выбор товара в списке добавления: модифицируется ссылка, -->
        <!-- ведущая на функцию добавления, нажимается, подгрузка товаров -->
        $("#add-item-select").on("change", '#item_id', function () {
            var item_id = +$(this).attr('value');
            var href = '/admin/carts/<%= @cart.id%>/add_item?item_id=' + item_id;
            $('#add-item-link').attr('href', href).click();
            $(this).prop('selectedIndex', 0);
        });
        <!-- реакция на изменение количества товара: -->
        <!-- пересчет всего, чего можно, отправка формы -->
        $("#container").on("keyup", ".quantity", function () {
            var quantity = +$(this).val();
            var line_item = $(this).closest("tr");
            var cost = line_item.find('.cost');
            var price = +line_item.find('.price').html();
            var discount = +$("#discount").val();
            var cost_old = +cost.html();
            var cost_new = price * quantity;
            cost.html(cost_new);
            var total = $('#total');
            var total_old = +total.html();
            var total_new = total_old + cost_new - cost_old;
            total.html(total_new);
            var total_discount = Math.round(total_new * (100 - discount) / 100);
            $('#total-discount').html(total_discount);
            var total_discount_delivery = $('#total-discount-delivery');
            var total_discount_delivery_new = total_discount;
            if (!(total_discount > threshold)) {
                total_discount_delivery_new += delivery;
            }
            total_discount_delivery.html(total_discount_delivery_new);
            $("#discount").keyup();
            $('#submit').click();
        });
        <!-- реакция на выбор товара в списке добавления -->
        $("#container").on("mouseup", ".quantity", function () {
            $(this).keyup();
        });
        $("#container").on('click', ".delete", function () {
            var cost = +$(this).closest('tr').find('.cost').html();
            var total = $('#total');
            var total_old = +total.html();
            var total_new = total_old - cost;
            total.html(total_new);
            $(this).closest('tr').remove();
            $("#discount").keyup();
        });
    });
</script>
<div class= 'col-md-12 alert alert-info'>
  Порог доставки: <b id="threshold"><%= @threshold %></b> руб <br/>
  Стоимость доставки: <b id="delivery"><%= @delivery %></b> руб <br/>
  После сохранения заказ обретет статус "Принят".
</div>
<div id="order-cart" class='span8'>
  <%= form_for [:admin, @cart], remote: true do |f| %>
      <%= link_to 'добавить', add_item_admin_cart_path(@cart, :item_id => @items[1].id), :remote => true, :id => "add-item-link", :style => "display:none;" %>
      <div id="add-item-select">
        <%= select_tag :item_id, options_from_collection_for_select(@items, :id, :title), :prompt => "Добавьте товар" %>
      </div>
      <div id=container>
        <% unless @cart.line_items.empty? %>
            <table id="items" class="table table-condensed">
              <tbody>
              <%= f.fields_for :line_items do |builder| %>
                  <% render builder.object, :f => builder %>
              <% end %>
              <tr>
                <td colspan=4 class="right">
                  Всего: <b id="total"><%= @cart.total %></b>р
                </td>
                <td></td>
              </tr>
              <tr>
                <td colspan=4 class="right">
                  Всего + скидка: <b id="total-discount"><%= @total_discount %></b>р
                </td>
                <td class="center">
                </td>
              </tr>
              <tr>
                <td colspan="4" class="right">
                  Всего + скидка + доставка: <b id='total-discount-delivery'><%= @total_discount_delivery %></b>р
                </td>
                <td></td>
              </tr>
              </tbody>
            </table>
        <% end %>
      </div>

      <div style="display:none;">
        <%= f.submit :id => 'submit' %>
      </div>
  <% end %>

  <%= form_for [:admin, @order], html: {class: 'form-horizontal'} do |f| %>
      <%= f.hidden_field :status  %>
      <%= f.error_messages %>

      <fieldset id=order-form>
        <legend>Данные клиента:</legend>
        <div class="form-group">
          <label class="control-label" for="discount">Скидка</label>

          <div class="controls">
            <%= f.number_field :discount, :in => 0..100, style: 'width:35px;', id: "discount" %>%
          </div>
        </div>

        <div class="form-group">
          <label class="control-label" for="order_name">ФИО</label>

          <div class="controls">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label" for="order_phone">Телефон</label>

          <div class="controls">
            <%= f.text_field :phone, :placeholder => "9110001122" %>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label" for="order_address">Адрес</label>

          <div class="controls">
            <%= f.text_area :address, :rows => 2, :placeholder => "Улица, дом, квартира" %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label" for="order_email">Email</label>

          <div class="controls">
            <%= f.email_field :email %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label" for="order_pay_type">Метод оплаты</label>

          <div class="controls">
            <%= f.select :pay_type, Order::PAYMENT_TYPES %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label" for="order_comment">Комментарий менеджера</label>

          <div class="controls">
            <%= f.text_area :manager_comment, :placeholder => "Комментарий менеджера", :rows => 2 %>

          </div>
        </div>
        <div class="form-actions">
          <%= f.submit 'Принять заказ', class: 'btn btn-default btn-primary' %>
        </div>
      </fieldset>
  <% end %>
</div>