config/routes.rb
Shopstr::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  devise_scope :users do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  resources :authentications, :only => [:destroy, :create, :index]
  resources :carts, :only => [:update, :destroy]
  resources :items, :only => :show
  resources :line_items, :only => [:create, :destroy]
  resources :orders, :only => [:new, :show,  :create]
  resources :pages , :only => [:home, :search, :show]
  resources :sections, :only => :show do
    get :filter, :on => :member
  end
  resources :users, :only => :show


  namespace :admin do
    resources :sections do
      get :trigger, :on => :member
      get :autocomplete, :on => :member
      resources :items
      resources :parameters
      collection { post :sort }

    end
    resources :amounts
    resources :line_items
    resources :carts do
      get :add_item, :on => :member
    end
    resources :users, :path => "/users" do
      get :trigger, :on => :member
    end
    resources :orders do
      get :add_item, :on => :member
      get :cancel, :on => :member
      get :complete, :on => :member
    end
    resources :items do
      get :who_bought, :on => :member
      get :duplicate, :on => :member
      get :trigger, :on => :member
      collection { get :parameters_list }
      collection { post :sort }
      collection { post :massacre }
    end
    resources :images
    resources :parameters do
      get :trigger, :on => :member
      collection { post :sort }
      resources :amounts
      collection { get :items_list }
    end
    resources :settings do
      collection do
        put 'update'
      end
    end
    resources :groups do
      resources :users
    end
    resources :pages do
      get :trigger, :on => :member
    end
  end

  get '/auth/:provider/callback' => 'authentications#create'
  #Page.enabled.each do |page|
  #  get "/#{page.uri}" => "pages#show", :id => page.id
  #end
  get '/search', :to => 'pages#search'
  get '/admin', :to => 'admin/pages#home'
  root :to => 'pages#home'
  get '*a', :to => 'errors#routing'
end

app/models/section.rb
# -*- encoding : utf-8 -*-
class Section < ActiveRecord::Base
  #attr_accessible :title, :parent_id, :level, :description, :keywords
  attr_protected
  validates :title, :presence => true,
            :length => {:maximum => 50},
            :uniqueness => true
  validates :parent_id, :numericality => true

  has_many :items, :dependent => :destroy
  has_and_belongs_to_many :parameters
  has_many :amounts, :through => :items, :dependent => :destroy
  #has_and_belongs_to_many :amounts
  TYPES= [["Строка", 0], ["Число", 1], ["Логика", 2]]

  #счетчик активных товаров и вложенные категории
  default_scope { joins("LEFT JOIN items items1 ON items1.section_id = sections.id AND items1.enabled='t'")
                .joins("LEFT JOIN items items2 ON items2.section_id = sections.id")
                .select("sections.*, count(distinct items1.id) as enabled_items, count(distinct items2.id) as all_items")
                .group("sections.id")
                .includes(:children)
                }
  has_many :children, :class_name => 'Section', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Section'

  def self.tree(full=false)
    beginner=Section.first

    if beginner
      tree=[]<<beginner
      result_tree=structurizer(tree,beginner.children)
      if full
        result_tree
      else
        result_tree.delete(beginner)
        if result_tree.size>0
          result_tree
        end
      end
    end
  end

  private
  def self.structurizer(tree,parents)
    for parent in parents
      tree<<parent
      structurizer(tree,parent.children)
    end
    tree
  end
end

app/controllers/admin/sections_controller.rb
# -*- encoding : utf-8 -*-
class Admin::SectionsController < Admin::BaseController
  def index
    @title = "Категории"
    @sections=Section.tree
    store_location
  end

  def show
    @cart=current_cart
    @section = Section.find(params[:id])
    @items=@section.items.page(params[:page]).per(10)
    @title=@section.title
    @parameters=@section.parameters
    @sections=Section.tree
  end

  def new
    @title="Создание новой категории"
    @sections=Section.tree(true)
    @section=Section.new
    @parameters=Parameter.all
    render '_form'
  end

  def create
    @section = Section.new(params[:section])
    @section.parameters= Parameter.find(params[:parameter_ids]) if params[:parameter_ids]

    # добавляем уровень вложенности в новую секцию
    @section.level=@section.parent.level+1

    if @section.save
      flash[:success] = "Категория создана!"
      redirect_to admin_sections_path
    else
      @title="Создание новой категории"
      @sections=Section.tree(true)
      @parameters=Parameter.all
      @selected_parameters=@section.parameters
      render '_form'
    end
  end

  def edit
    @title = "Изменение категории"
    @section = Section.find(params[:id])
    @parameters=Parameter.all
    @selected_parameters=@section.parameters
    @sections=Section.tree(true)
    render '_form'
  end

  def update
    @section = Section.find(params[:id])
    @section.parameters= Parameter.find(params[:parameter_ids]) if params[:parameter_ids]

    @section.level=Section.find(params[:section][:parent_id]).level+1
    params[:section][:level]="#{@section.level}"

    if @section.update_attributes(params[:section])
      section_references_actualizer(@section)
      flash[:success] = "Категория изменена"
      redirect_back_or admin_sections_path
    else
      @title = "Изменение категории"
      render '_form'
    end
  end

  def destroy
    no_bought=false
    @id=params[:id]
    @section=Section.find(@id)
    @section.items.each do |i|
      unless i.line_items.empty?
        break
      end
      no_bought=true
    end
    title=@section.title
    if no_bought.nil?
      #section.destroy
      flash.now[:success] = "Категория <b>#{title}</b> и товары в ней были успешно удалены."
    else
      flash.now[:error] = "Категория <b>#{title}</b> не может быть удалена, т.к. хотя бы один товар в ней был куплен."
    end
    respond_to :js
  end

  def trigger
    @section= Section.find(params[:id])
    method= params[:field]
    value= @section.send(method) ? false : true
    if @section.update_attribute(method, value)
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def sort
    params[:section].each_with_index do |id, index|
      Section.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

end

app/controllers/sections_controller.rb
# -*- encoding : utf-8 -*-
class SectionsController < ApplicationController
  before_filter :sections_tree, :pages_list

  def show
    @section = Section.find(params[:id])
    @title=@section.title
    @parameters=@section.parameters.where(:filterable => true).order(:kind)
    @items=@section.items.enabled.order(sort_column + " " + sort_direction).page(params[:page]).per(per_value)
    @cart=current_cart

    #meta
    @meta_title=@section.meta_title
    @meta_description=@section.meta_description
    @meta_keywords=@section.meta_keywords
  end

  def filter
    section=Section.find(params[:id])
    @items=section.items.order(sort_column + " " + sort_direction)

    #price
    from=params[:price][:from].to_i.abs
    to=params[:price][:to].to_i.abs
    unless from==0 and to==0
      if to==0
        to=1000000
      else
        to, from=from, to if from>to
      end
      @items=@items.where(:price => (from..to))
    end

    params[:amounts].each do |param_id, values|
      param=Parameter.find(param_id)
      case param.kind
        when 0
          items_str=[]
          values.each do |value|
            amount=Amount.find(value)
            items_str+=amount.items
          end
          @items&=items_str
        when 1
          from=values[:from].to_i.abs
          to=values[:to].to_i.abs
          unless from==0 and to==0
            if to==0
              to=1000000
            else
              if from>to
                to, from=from, to if from>to
              end
            end
            amounts=Amount.where(:num => (from..to))
            items_num=[]
            amounts.each do |amount|
              items_num+=amount.items
            end
            @items&=items_num
          end
        when 2
          unless values.blank?
            amount=Amount.find_by_id(values)
            @items&=amount.items
          end
      end
    end
    @items=Kaminari.paginate_array(@items).page(params[:page]).per(5)
  end

end

app/helpers/sections_helper.rb
# -*- encoding : utf-8 -*-
module SectionsHelper
  #определятор активной ссылки
  def section_link(text, section, enabled_items, html_options={})
    active_section_id=params[:id]
    if section.id.to_s==active_section_id
      #current link
      raw("<li class='active'>"<<link_to(text, section, html_options)<<"</li>")
    else
      if enabled_items>0
        raw("<li>"<<link_to(text, section, html_options)<<"</li>")
      else
        raw("<li>"<<content_tag(:a, text, html_options)<<"<li>")
      end
    end
  end
end





app/views/admin/sections/_form.html.erb
<%= form_for [:admin, @section], :html => {:class => 'form-horizontal'} do |f| %>
    <%= f.error_messages %>

    <div class="form-group">
      <label class="control-label" for="section_title">Название</label>

      <div class="controls">
        <%= f.text_field :title, :class => 'title span7' %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label" for="section_enabled">Активна?</label>

      <div class="controls">
        <%= f.check_box :enabled %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label" for="section_parent_id">Родительская категория</label>

      <div class="controls">
        <%= collection_select(:section, :parent_id, @sections, :id, :title) %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label" for="section_meta_title">Meta-title</label>

      <div class="controls">
        <%= f.text_field :meta_title, class: 'span7' %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label" for="section_meta_keywords">Meta-keywords</label>

      <div class="controls">
        <%= f.text_field :meta_keywords, class: 'span7' %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label" for="section_meta_description">Meta-description</label>

      <div class="controls">
        <%= f.text_area :meta_description, :rows => 3, class: 'span7' %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label" for="paraneter_ids_">Параметры</label>

      <div class="controls">
        <%= select_tag("parameter_ids[]", options_for_select(@parameters.collect { |par| [par.title, par.id] }, @section.parameters.collect { |par| par.id }), {:multiple => true, :size => 6}) %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label" for="section_description">Описание категории</label>

      <div class="controls">
        <%= f.text_area :description, :rows => 3, class: 'span7' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit "Сохранить", class: 'btn btn-default btn-primary' %>
    </div>

<% end %>

app/views/admin/sections/_section.html.erb
<% unless section.level==1 %>
    <%= content_tag_for :tr, section do %>
        <td class="handle"><i class="glyphicon glyphicon-move"></i></td>
        <td><%= link_to "#{section.title}", admin_section_path(section), :style => "margin-left:#{(section.level*10-20)}px" %>
          <span title="Активных товаров"><%= " #{section.enabled_items.to_i}/#{section.all_items}" %></span></td>
        <td><%= link_to raw("<i class='glyphicon glyphicon-plus-sign'></i>"), new_admin_section_item_path(section), title: 'Добавить товар в эту категорию', :class => 'btn btn-default btn-xs' %></td>
        <% if section.enabled? %>
            <td><%= link_to raw("<i class='glyphicon glyphicon-off'></i>"), trigger_admin_section_path(id: section, field: :enabled), title: 'Выключить', remote: true, class: "active btn btn-default btn-xs enabled" %></td>
        <% else %>
            <td><%= link_to raw("<i class='glyphicon glyphicon-off'></i>"), trigger_admin_section_path(id: section, field: :enabled), title: 'Включить', remote: true, class: "btn btn-default btn-xs enabled" %></td>
        <% end %>
        <td><%= link_to raw("<i class='glyphicon glyphicon-pencil glyphicon glyphicon-white'></i>"), edit_admin_section_path(section), title: 'Редактировать', :class => 'btn btn-default btn-warning btn-xs' %></td>
        <td><%= link_to raw("<i class='glyphicon glyphicon-trash glyphicon glyphicon-white'></i>"), admin_section_path(section), :remote=> true, method: :delete, :confirm => 'Удалить?', :class => 'btn btn-default btn-danger btn-xs delete' %></td>
    <% end %>
<% end %>

app/views/admin/sections/destroy.js.erb
$('.flash').remove();
$('body').append('<%= escape_javascript (render partial: 'layouts/flash', locals: { flash: flash}) %>');
show_flashes();
<% if @section %>
$('#item_<%= @id%>').replaceWith('<%= escape_javascript( render @section)%>');
<% else %>
$('#item_<%= @id%>').remove();
<% end %>

app/views/admin/sections/index.html.erb
<script>
    $(function () {
        $('#sects').sortable({
            axis:'y',
            handle:'.handle',
            update:function () {
                $.post($(this).data('update-url'), $(this).sortable('serialize'));
            }
        });
    });
</script>
<%= link_to raw("<i class='glyphicon glyphicon-plus glyphicon glyphicon-white'></i>категорию"), new_admin_section_path, :class => 'btn btn-default btn-primary add-button' %>
<div id="sections">
  <% unless @sections.blank? %>
      <table class="table auto table-condensed">
        <tbody id="sects" data-update-url="<%= sort_admin_sections_url %>">
        <%= render @sections %>
        </tbody>
      </table>
  <% end %>
</div>






app/views/admin/sections/show.html.erb
<script>
    $(function () {
        $('.delete').click(function () {
            $(this).closest('tr').hide();
        });
    });
</script>
<%= link_to raw("<i class='glyphicon glyphicon-plus-sign'></i>товар"), new_admin_section_item_path(@section), :class => 'btn btn-default' %>

<% if @items.blank? %>
    <h2>Пока пусто</h2>
<% else %>
    <%= paginate @items %>
    <div id="items">
      <table class="table auto table-condensed">
        <tbody>
        <%= render @items %>
        </tbody>
      </table>
    </div>
<% end %>

app/views/admin/sections/trigger.js.erb
var link=$('#section_<%=@section.id %>').find('.enabled');
<% if @section.enabled? %>
link.addClass('active').attr('title','Выключить');
<% else %>
link.removeClass('active').attr('title','Включить');
<% end %>