config/routes.rb
Shopstr::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  devise_scope :users do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  resources :authentications, :only => [:destroy, :create, :index]
  resources :carts, :only => [:update, :destroy]
  resources :items, :only => :show
  resources :line_items, :only => [:create, :destroy]
  resources :orders, :only => [:new, :show,  :create]
  resources :pages , :only => [:home, :search, :show]
  resources :sections, :only => :show do
    get :filter, :on => :member
  end
  resources :users, :only => :show


  namespace :admin do
    resources :sections do
      get :trigger, :on => :member
      get :autocomplete, :on => :member
      resources :items
      resources :parameters
      collection { post :sort }

    end
    resources :amounts
    resources :line_items
    resources :carts do
      get :add_item, :on => :member
    end
    resources :users, :path => "/users" do
      get :trigger, :on => :member
    end
    resources :orders do
      get :add_item, :on => :member
      get :cancel, :on => :member
      get :complete, :on => :member
    end
    resources :items do
      get :who_bought, :on => :member
      get :duplicate, :on => :member
      get :trigger, :on => :member
      collection { get :parameters_list }
      collection { post :sort }
      collection { post :massacre }
    end
    resources :images
    resources :parameters do
      get :trigger, :on => :member
      collection { post :sort }
      resources :amounts
      collection { get :items_list }
    end
    resources :settings do
      collection do
        put 'update'
      end
    end
    resources :groups do
      resources :users
    end
    resources :pages do
      get :trigger, :on => :member
    end
  end

  get '/auth/:provider/callback' => 'authentications#create'
  #Page.enabled.each do |page|
  #  get "/#{page.uri}" => "pages#show", :id => page.id
  #end
  get '/search', :to => 'pages#search'
  get '/admin', :to => 'admin/pages#home'
  root :to => 'pages#home'
  get '*a', :to => 'errors#routing'
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :item
  belongs_to :page
  default_scope { order('created_at DESC') }
  has_attached_file :photo, :styles => {:medium => "150x200", :thumb => "45x>"}
  before_post_process :rename_photo

  def rename_photo
    #avatar_file_name - important is the first word - avatar - depends on your column in DB table
    extension = File.extname(photo_file_name).downcase
    self.photo.instance_write :file_name, "#{Time.now.to_i.to_s}#{extension}"
  end
end

app/controllers/admin/images_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ImagesController < Admin::BaseController

  def create
    @image=Image.create(:photo=>params[:file])
    respond_to :js
  end

  def destroy
    Image.destroy(params[:id])
    respond_to :js
  end

end


app/views/admin/images/_image.erb
<div class="span2 cell"
  <% if image.main? %>
        style="border-color:green;"
        <% else %>
        style="border-color:transparent;"
        <% end %>
>
  <div class="img-title">
    <% image.photo_file_name %> <%= image.photo_file_size/1024 %> кБ
    <%= link_to 'X', admin_image_path(image), method: :delete, remote: true, id: image.id, class: "badge badge-inverse delete" %>
  </div>
  <div class="img">
    <%= image_tag image.photo.url(:medium), title: image.photo_file_name %>
  </div>
</div>

app/views/admin/images/_page_image.erb
<div class="span2 cell"
  <% if image.main? %>
        style="border-color:green;"
        <% else %>
        style="border-color:transparent;"
        <% end %>
>
  <div class="img-title">
    <% image.photo_file_name %> <%= image.photo_file_size/1024 %> кБ
    <%= link_to 'X', admin_image_path(image), method: :delete, remote: true, id: image.id, class: "badge badge-inverse delete" %>
    <%= link_to '↵', "#", class: "badge badge-inverse insert" %>
  </div>
  <div class="img">
    <%= image_tag image.photo.url %>
  </div>
</div>

app/views/admin/images/create.js.erb
<%=@image.id %>:<%= @image.photo.url(:medium) %>:<%= @image.photo.url %>